# Generated by Django 6.0.4 on 2026-05-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.CharField(default='2024-25', max_length=10)),
                ('itr_type', models.CharField(default='ITR-1', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'In Progress'), ('review', 'Under Review'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('regime', models.CharField(choices=[('old', 'Old Tax Regime'), ('new', 'New Tax Regime'), ('ai_recommended', 'AI Recommended')], default='ai_recommended', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_liability', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_or_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_regime_suggestion', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tax_year')},
            },
        ),
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra_exemption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('form16_uploaded', models.BooleanField(default=False)),
                ('freelance_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_gains_stcg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_gains_ltcg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='itr.itrfiling')),
            ],
        ),
        migrations.CreateModel(
            name='DeductionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('epf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lic_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_loan_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nsc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance_self', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance_parents', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nps_80ccd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NPS (80CCD)')),
                ('home_loan_interest_24b', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('education_loan_80e', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation_80g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_interest_80tta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='itr.itrfiling')),
            ],
        ),
    ]
