# Generated by Django 6.0.4 on 2026-05-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('existing_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservative (Safe)'), ('moderate', 'Moderate (Balanced)'), ('aggressive', 'Aggressive (High Growth)')], default='moderate', max_length=20)),
                ('primary_goal', models.CharField(choices=[('emergency_fund', 'Build Emergency Fund'), ('home_purchase', 'Buy a Home'), ('retirement', 'Retire Comfortably'), ('education', 'Child Education'), ('wealth_creation', 'General Wealth Creation')], default='wealth_creation', max_length=30)),
                ('goal_timeline_years', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('suggested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_return', models.CharField(blank=True, max_length=50)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('tax_benefit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='financial.financialprofile')),
            ],
        ),
    ]
